--схема ETL

GRANT SELECT ON etl.npf_person TO INS WITH GRANT OPTION;
GRANT SELECT ON etl.npf_ops_policy TO INS WITH GRANT OPTION;
GRANT SELECT ON etl.npf_product TO INS WITH GRANT OPTION;
GRANT SELECT ON etl.npf_status_ref TO INS WITH GRANT OPTION;
GRANT SELECT ON etl.tmp_ops_nums_for_delete TO INS WITH GRANT OPTION;