--схема INS_DWH

GRANT SELECT ON INS_DWH.dm_t_sales_channel TO INS WITH GRANT OPTION;
GRANT SELECT ON INS_DWH.dm_p_pol_header TO INS WITH GRANT OPTION;
GRANT SELECT ON INS_DWH.t_fc_epg TO INS WITH GRANT OPTION;
GRANT SELECT ON INS_DWH.fc_pay_doc TO INS WITH GRANT OPTION;