CREATE OR REPLACE FORCE VIEW V_AG_CONTACT_INFO_FACADE AS
SELECT "NUM","NAME","FIRST_NAME","MIDDLE_NAME","BIRTH_DATE","SER_PASP","NUM_PASP","ISSUE_DATE_PASP","PLACE_ISSUE_PASP","NUM_PENS","IIN_CONTACT","REGION_NAME","REG_TYPE","PROVINCE_NAME","PRV_TYPE","CITY_NAME","CT_TYPE","DST_TYPE","DISTRICT_NAME","STREET_NAME","STR_TYPE","HOUSE_NR","BUILDING_NAME","APPARTMENT_NR","ZIP","ADDRESS_NAME","BIK_BANK","NAME_BANK","RACCOUNT_BANK","LICACCOUNT_BANK","CONTACT_ID","AG_CONTRACT_HEADER_ID","NUM_AD","CATEGORY_NAME","DATE_BEGIN","DOC_DATE_PAY_PROP" FROM ins.v_ag_contact_info;

