create view insi.v_payment_contact_info_facade as
select num
      ,name
      ,first_name
      ,middle_name
      ,birth_date
      ,ser_pasp
      ,num_pasp
      ,issue_date_pasp
      ,place_issue_pasp
      ,num_pens
      ,iin_contact
      ,region_name
      ,reg_type
      ,province_name
      ,prv_type
      ,city_name
      ,ct_type
      ,dst_type
      ,district_name
      ,street_name
      ,str_type
      ,house_nr
      ,building_name
      ,appartment_nr
      ,zip
      ,address_name
      ,bik_bank
      ,name_bank
      ,corraccount_bank
      ,raccount_bank
      ,licaccount_bank
      ,inn_bank
      ,contact_id
      ,ag_contract_header_id
      ,num_ad
      ,category_name
      ,date_begin
  from ins.v_payment_contact_info;
