create or replace force view vgo_gate_trans as
select  TRANS_ID as CODE         ,
  TRANS_DATE         ,
  TRANS_FUND_ID      ,
  TRANS_AMOUNT       ,
  DT_ACCOUNT_ID      ,
  CT_ACCOUNT_ID      ,
  IS_ACCEPTED        ,
  A1_DT_URE_ID       ,
  A1_DT_URO_ID       ,
  A1_CT_URE_ID       ,
  A1_CT_URO_ID       ,
  A2_DT_URE_ID       ,
  A2_DT_URO_ID       ,
  A2_CT_URE_ID       ,
  A2_CT_URO_ID       ,
  A3_DT_URE_ID       ,
  A3_DT_URO_ID       ,
  A3_CT_URE_ID       ,
  A3_CT_URO_ID       ,
  A4_DT_URE_ID       ,
  A4_DT_URO_ID       ,
  A4_CT_URE_ID       ,
  A4_CT_URO_ID       ,
  A5_DT_URE_ID       ,
  A5_DT_URO_ID       ,
  A5_CT_URE_ID       ,
  A5_CT_URO_ID       ,
  TRANS_TEMPL_ID     ,
  ACC_CHART_TYPE_ID  ,
  ACC_FUND_ID        ,
  ACC_AMOUNT         ,
  ACC_RATE           ,
  OPER_ID            ,
  REG_DATE           ,
  TRANS_QUANTITY     ,
  SOURCE             ,
  NOTE               ,
  EXT_ID             ,
  OBJ_URE_ID         ,
  OBJ_URO_ID         
   from 
INS.TRANS;

