CREATE OR REPLACE PACKAGE PKG_AGENT_CATEGORY IS

  FUNCTION GetAgCategory(p_rec NUMBER) RETURN VEN_AG_CATEGORY_AGENT %ROWTYPE;

END PKG_AGENT_CATEGORY;
/
CREATE OR REPLACE PACKAGE BODY PKG_AGENT_CATEGORY IS

  FUNCTION GetAgCategory(p_rec NUMBER) RETURN VEN_AG_CATEGORY_AGENT %ROWTYPE IS
    CURSOR cur(p_id NUMBER) IS
      SELECT * FROM VEN_AG_CATEGORY_AGENT WHERE AG_CATEGORY_AGENT_ID = p_id;
  
    rec VEN_AG_CATEGORY_AGENT%ROWTYPE;
  BEGIN
  
    OPEN cur(p_rec);
    FETCH cur
      INTO rec;
  
    IF (cur%NOTFOUND)
    THEN
      CLOSE cur;
      RETURN NULL;
    END IF;
  
    CLOSE cur;
    RETURN rec;
  EXCEPTION
    WHEN OTHERS THEN
      RETURN NULL;
  END GetAgCategory;

END PKG_AGENT_CATEGORY;
/
