create or replace force view ins_dwh.trans_templ as
select "TRANS_TEMPL_ID","ENT_ID","FILIAL_ID","EXT_ID","ACC_CHART_TYPE_ID","BRIEF","CT_ACC_DEF_RULE_ID","CT_ACCOUNT_ID","CT_ACC_TYPE_TEMPL_ID","CT_ANALYTIC_TYPE_ID","CT_REV_ACC_CHART_TYPE_ID","CT_URE_ID","CT_URO_ID","DATE_TYPE_ID","DT_ACC_DEF_RULE_ID","DT_ACCOUNT_ID","DT_ACC_TYPE_TEMPL_ID","DT_ANALYTIC_TYPE_ID","DT_REV_ACC_CHART_TYPE_ID","DT_URE_ID","DT_URO_ID","EXPORT_TYPE_ID","FUND_TYPE_ID","IS_ACCEPTED","IS_EXPORT","NAME","NOTE","QTY_TYPE_ID","SUMM_FUND_TYPE_ID","SUMM_TYPE_ID" from ins.ven_trans_templ;

