create or replace force view ins_dwh.v_reserves_vs_profit_mart as
select "PK","Current Policy ID","POL_HEADER_ID","ID","Cover ID","Active","Policy number","Policy_version","Risk name progr","Risk name","Policy Type ID","Accrual_Period_name","Accrstatus","Sex(Insurer)","Sex(Policyholder)","START_DATE_RISK","END_DATE_RISK","Date from 1","Date to","Cover value","Cover premium","Pay period name","Med ep coef","Med em coef","Ep non med","Em non med","I sport coef","I prof coef","Re med ep coef","Re med em coef","Re ep non med","Re em non med","Re sport coef","Re prof coef","Policy note","Date of birth(Insurer)","Date of birth(Policyholder)","Date of death(Insurer)","Insurer id","Currency","Insurance period","Mort discount","Ii rate","Date Cancel","Policy holder","Corporate policy type","FOR_RE","Reinsured","Date orig","Year com","Charge Premium","Risk type gaap","Loading","Ii rate benefit","Benefit period name","Date start benefit","Date benefit end","Benefit period","Date guaranteed end","Guaranteed period","Date end premium","Premium period","Acquisition total","Inst start","Inst end","Commission","actuar_age","p_cover_id","p_policy_id","p_pol_header_id","risk_ext_id","policy_ext_ID","Policy insurer","Pay period coef","bank product","product name","SALES_CH","Date from","Status","Death Table","Commission for UPR","Commission for MSFO","Acquisition","Sex (Child)","Date of birth (Child)","K coef m (child)","S coef m (child)","K coef nm (child)","S coef nm (child)","Sport coef (child)","Prof coef (child)","K coef m re (child)","S coef m re (child)","K coef nm re (child)","S coef nm re (child)","Sport coef re (child)","Prof coef re (child)","Change","Years before change","Premium before change","Pay period name before change","Stop Date","Renewal Date","IS_AVTOPROLONGATION","PAYMENT_PERIOD","IDS","DATE_LAST_VERSION","TYPE_INSURANCE","SUR","BRIEF","IS_GROUP_FLAG","Номер ДС","Заявление","АД","ID_АД","Id Дс","Валюта","Страхователь","Тип страхователя","Кол-во застрахованных по ДС","Статус посл версии","DECLINE_REASON","Дата расторжения","Регион","Агентство","Рассрочка по Акт версии","NUMBER_OF_PAYMENTS","Год действия","Дата начала ДС","Дата окончания ДС","Продукт","Страховая сумма по акт версии","ID Риска","Программа","FIST_TO_PAY_DATE","IS_MANDATORY","PROGRAM_START","PROGRAM_END","VERSION_NUM","VERSION_ORDER_NUM"
  from ins_dwh.reserves_vs_profit pr
 where pr."Active" = 1
union all
-- Неактивные версии с рисками, попадающими в журнал проводок
select "PK","Current Policy ID","POL_HEADER_ID","ID","Cover ID","Active","Policy number","Policy_version","Risk name progr","Risk name","Policy Type ID","Accrual_Period_name","Accrstatus","Sex(Insurer)","Sex(Policyholder)","START_DATE_RISK","END_DATE_RISK","Date from 1","Date to","Cover value","Cover premium","Pay period name","Med ep coef","Med em coef","Ep non med","Em non med","I sport coef","I prof coef","Re med ep coef","Re med em coef","Re ep non med","Re em non med","Re sport coef","Re prof coef","Policy note","Date of birth(Insurer)","Date of birth(Policyholder)","Date of death(Insurer)","Insurer id","Currency","Insurance period","Mort discount","Ii rate","Date Cancel","Policy holder","Corporate policy type","FOR_RE","Reinsured","Date orig","Year com","Charge Premium","Risk type gaap","Loading","Ii rate benefit","Benefit period name","Date start benefit","Date benefit end","Benefit period","Date guaranteed end","Guaranteed period","Date end premium","Premium period","Acquisition total","Inst start","Inst end","Commission","actuar_age","p_cover_id","p_policy_id","p_pol_header_id","risk_ext_id","policy_ext_ID","Policy insurer","Pay period coef","bank product","product name","SALES_CH","Date from","Status","Death Table","Commission for UPR","Commission for MSFO","Acquisition","Sex (Child)","Date of birth (Child)","K coef m (child)","S coef m (child)","K coef nm (child)","S coef nm (child)","Sport coef (child)","Prof coef (child)","K coef m re (child)","S coef m re (child)","K coef nm re (child)","S coef nm re (child)","Sport coef re (child)","Prof coef re (child)","Change","Years before change","Premium before change","Pay period name before change","Stop Date","Renewal Date","IS_AVTOPROLONGATION","PAYMENT_PERIOD","IDS","DATE_LAST_VERSION","TYPE_INSURANCE","SUR","BRIEF","IS_GROUP_FLAG","Номер ДС","Заявление","АД","ID_АД","Id Дс","Валюта","Страхователь","Тип страхователя","Кол-во застрахованных по ДС","Статус посл версии","DECLINE_REASON","Дата расторжения","Регион","Агентство","Рассрочка по Акт версии","NUMBER_OF_PAYMENTS","Год действия","Дата начала ДС","Дата окончания ДС","Продукт","Страховая сумма по акт версии","ID Риска","Программа","FIST_TO_PAY_DATE","IS_MANDATORY","PROGRAM_START","PROGRAM_END","VERSION_NUM","VERSION_ORDER_NUM"
  from ins_dwh.reserves_vs_profit pr
 where pr."Active" = 0
   and exists (select null
                 from trans_rep tr
                where tr.p_cover_id = pr."Cover ID"
              )
;

