CREATE OR REPLACE FORCE VIEW V_AGENT_REP_PCOVER_PAGENT_COM AS
SELECT PP.POL_HEADER_ID, 
    PP.POLICY_ID, 
    PC.P_COVER_ID, 
    TPLO_AGENT.ID AS T_PROD_LINE_OPTION_ID, 
    ARC.AGENT_REPORT_CONT_ID, 
    ARC.AGENT_REPORT_ID, 
    ARC.P_POLICY_AGENT_COM_ID 
  FROM P_POLICY_AGENT pa, 
    AS_ASSET ASS, 
    P_COVER PC, 
    P_POLICY PP, 
    T_PROD_LINE_OPTION TPLO, 
    AGENT_REPORT_CONT ARC, 
    P_POLICY_AGENT_COM ppac, 
    T_PROD_LINE_OPTION TPLO_AGENT, 
    T_PRODUCT_LINE TPL_AGENT 
 WHERE pa.p_policy_agent_id = ppac.P_POLICY_AGENT_ID 
   AND PP.POL_HEADER_ID = pa.POLICY_HEADER_ID 
 AND ASS.P_POLICY_ID = PP.POLICY_ID 
 AND PC.AS_ASSET_ID = ASS.AS_ASSET_ID 
 AND PC.T_PROD_LINE_OPTION_ID = TPLO.ID 
 AND ARC.P_POLICY_AGENT_COM_ID = ppac.P_POLICY_AGENT_COM_ID 
 AND ARC.POLICY_ID = PP.POLICY_ID 
 AND TPLO_AGENT.PRODUCT_LINE_ID = TPL_AGENT.ID 
 AND TPL_AGENT.ID = ppac.T_PRODUCT_LINE_ID 
 AND TPLO_AGENT.ID = TPLO.ID;

