CREATE OR REPLACE FORCE VIEW V_AGENT_REPORT_DAV_PCOVER AS
SELECT PPH.POLICY_HEADER_ID, 
    PPH.POLICY_ID, 
    PC.P_COVER_ID, 
    TPLO_AGENT.ID AS T_PROD_LINE_OPTION_ID, 
    ARC.AGENT_REPORT_DAV_CT_ID, 
    ARC.AGENT_REPORT_DAV_ID 
  FROM P_POLICY_AGENT pa, 
    VEN_P_POL_HEADER PPH, 
    AS_ASSET ASS, 
    P_COVER PC, 
    T_PROD_LINE_OPTION TPLO, 
    AGENT_REPORT_DAV_CT ARC, 
    P_POLICY_AGENT_COM ppac, 
    T_PROD_LINE_OPTION TPLO_AGENT, 
    T_PRODUCT_LINE TPL_AGENT 
 WHERE pa.p_policy_agent_id = ppac.P_POLICY_AGENT_ID 
   AND PPH.POLICY_HEADER_ID = pa.POLICY_HEADER_ID 
 AND ASS.P_POLICY_ID = pph.POLICY_ID 
 AND PC.AS_ASSET_ID = ASS.AS_ASSET_ID 
 AND PC.T_PROD_LINE_OPTION_ID = TPLO.ID 
 AND ARC.P_POLICY_AGENT_COM_ID = ppac.P_POLICY_AGENT_COM_ID 
 AND TPLO_AGENT.PRODUCT_LINE_ID = TPL_AGENT.ID 
 AND TPL_AGENT.ID = ppac.T_PRODUCT_LINE_ID 
 AND TPLO_AGENT.ID = TPLO.ID;

