CREATE OR REPLACE VIEW V_ASSET_COVER_LIFE
(p_cover_id, source_cover_id, p_policy_id, p_asset_header_id, as_asset_id, t_prod_line_option_id, start_date, end_date, ins_amount, premium, tariff, t_deductible_type_id, t_deduct_val_type_id, deductible_value, status_hist_id, ent_id, filial_id, old_premium, compensation_type, fee, number_of_payments, is_handchange_amount, is_handchange_premium, is_handchange_tariff, is_handchange_deduct, is_handchange_s_coef_nm, is_handchange_k_coef_nm, decline_date, decline_summ, is_decline_charge, is_decline_comission, is_handchange_decline, is_aggregate, pl_description, pl_product_line_id, ins_price, is_proportional, rvb_value, k_coef, s_coef, normrate_value, comments, insured_age, premium_all_srok, premia_base_type, added_summ, payed_summ, debt_summ, return_summ, accum_period_end_age, is_avtoprolongation, netto_tariff, k_coef_m, k_coef_nm, s_coef_m, s_coef_nm, decline_party_id, decline_reason_id, period_id, tariff_netto, is_handchange_fee, deathreate_id, product_ver_lob_id, pl_brief, t_lob_line_id, lob_brief, sh_brief, plt_brief, imaging, product_line_id, t_insurance_group_id, life_property, pl_sort_order)
AS
SELECT   pc.p_cover_id,
            pc.source_cover_id,
            aa.p_policy_id,
            aa.p_asset_header_id,
            pc.as_asset_id,
            pc.t_prod_line_option_id,
            pc.start_date,
            pc.end_date,
            pc.ins_amount,
            pc.premium,
            pc.tariff,
            pc.t_deductible_type_id,
            pc.t_deduct_val_type_id,
            pc.deductible_value,
            pc.status_hist_id,
            pc.ent_id,
            pc.filial_id,
            old_premium,
            compensation_type,
            pc.fee,
            pt.number_of_payments,
            pc.is_handchange_amount,
            pc.is_handchange_premium,
            pc.is_handchange_tariff,
            pc.is_handchange_deduct,
            pc.is_handchange_s_coef_nm,
            pc.is_handchange_k_coef_nm,
            pc.decline_date,
            pc.decline_summ,
            pc.is_decline_charge,
            pc.is_decline_comission,
            pc.is_handchange_decline,
            pl.is_aggregate,
            pl.description pl_description,
            pl.ID pl_product_line_id,
            pc.ins_price,
            is_proportional,
            pc.rvb_value,
            pc.k_coef,
            pc.s_coef,
            pc.normrate_value,
            comments,
            pc.insured_age,
            premium_all_srok,
            premia_base_type,
            pc.added_summ,
            pc.payed_summ,
            pc.debt_summ,
            pc.return_summ,
            accum_period_end_age,
            pc.is_avtoprolongation,
            netto_tariff,
            NVL (pc.k_coef_m, 0),
            NVL (pc.k_coef_nm, 0),
            NVL (pc.s_coef_m, 0),
            NVL (pc.s_coef_nm, 0),
            pc.decline_party_id,
            pc.decline_reason_id,
            pc.period_id,
            tariff_netto,
            is_handchange_fee,
            deathreate_id,
            pl.product_ver_lob_id,
            pl.brief pl_brief,
            ll.t_lob_line_id,
            ll.brief lob_brief,
            sh.brief sh_brief,
            plt.brief plt_brief,
            imaging,
            product_line_id,
            ig.t_insurance_group_id,
            ig.life_property,
            pl.sort_order pl_sort_order
     FROM   T_LOB_LINE ll,
            T_PRODUCT_LINE_TYPE plt,
            T_PRODUCT_LINE pl,
            T_PAYMENT_TERMS pt,
            P_POLICY pp,
            ins.document d,
            ins.doc_status_ref rf,
            AS_ASSET aa,
            P_COVER pc,
            T_PROD_LINE_OPTION plo,
            ven_status_hist sh,
            t_insurance_group ig
    WHERE       1 = 1
            AND aa.as_asset_id = pc.as_asset_id
            AND pp.policy_id = aa.p_policy_id
            AND pt.ID = pp.payment_term_id
            AND plo.ID = pc.t_prod_line_option_id
            AND pl.ID = plo.product_line_id
            AND ll.t_lob_line_id = pl.t_lob_line_id
            AND plt.product_line_type_id = pl.product_line_type_id
            AND sh.status_hist_id = pc.status_hist_id
            AND ll.insurance_group_id = ig.t_insurance_group_id
            AND pp.policy_id = d.document_id
            AND d.doc_status_ref_id = rf.doc_status_ref_id
            AND rf.brief != 'CANCEL';
