CREATE OR REPLACE FORCE VIEW V_ASSET_COVER AS
SELECT "BRIEF", "DESCRIPTION", "ID", "FOR_PREMIUM", "SORT_ORDER",
          "PRODUCT_ID", "ASSET_ID", "FOR_RE", "PLT_DESC", "P_COVER_ID",
          "AS_ASSET_ID", "T_PROD_LINE_OPTION_ID", "START_DATE", "END_DATE",
          "INS_AMOUNT", "PREMIUM", "TARIFF", "T_DEDUCTIBLE_TYPE_ID",
          "T_DEDUCT_VAL_TYPE_ID", "DEDUCTIBLE_VALUE", "STATUS_HIST_ID",
          "ENT_ID", "FILIAL_ID", "OLD_PREMIUM", "COMPENSATION_TYPE", "FEE",
          "IS_HANDCHANGE_AMOUNT", "IS_HANDCHANGE_PREMIUM",
          "IS_HANDCHANGE_TARIFF", "IS_HANDCHANGE_DEDUCT", "DECLINE_DATE",
          "DECLINE_SUMM", "IS_DECLINE_CHARGE", "IS_DECLINE_COMISSION",
          "IS_HANDCHANGE_DECLINE", "IS_AGGREGATE", "INS_PRICE", "EXT_ID",
          "IS_PROPORTIONAL", "RVB_VALUE", "K_COEF", "S_COEF",
          "NORMRATE_VALUE", "COMMENTS", "INSURED_AGE", "ACCUM_END_AGE",
          "PREMIUM_ALL_SROK", "PREMIA_BASE_TYPE", "ADDED_SUMM", "PAYED_SUMM",
          "DEBT_SUMM", "RETURN_SUMM", "ACCUM_PERIOD_END_AGE",
          "IS_AVTOPROLONGATION", "NETTO_TARIFF", "K_COEF_M", "K_COEF_NM",
          "S_COEF_M", "S_COEF_NM", "DECLINE_PARTY_ID", "DECLINE_REASON_ID",
          "PERIOD_ID", "TARIFF_NETTO", "IS_HANDCHANGE_FEE", "IMAGING",
          "PRODUCT_LINE_ID"
     FROM TABLE
             (pkg_xx_as_asset.product_line_info
                                            (pkg_xx_as_asset.get_as_asset_id)
             );

