CREATE OR REPLACE FORCE VIEW V_AS_ASSET_CURR_VER AS
select A."SD_1",A."AS_ASSET_ID",A."P_ASSET_HEADER_ID",A."ENT_ID",A."FILIAL_ID",A."STATUS_HIST_ID",A."P_POLICY_ID",A."INS_AMOUNT",A."INS_PREMIUM",A."NOTE",A."CONTACT_ID",A."START_DATE",A."END_DATE",A."FEE",A."INS_PRICE",A."EXT_ID",A."T_DEDUCTIBLE_TYPE_ID",A."T_DEDUCT_VAL_TYPE_ID",A."DEDUCTIBLE_VALUE",A."INS_VAR_ID",A."NAME",A."IS_FIRST_EVENT",A."INS_LIMIT" from
(
  SELECT MAX(A.AS_ASSET_ID) OVER (PARTITION BY A.P_ASSET_HEADER_ID) AS sd_1,A.*
       FROM AS_ASSET A
) a WHERE a.sd_1 = a.AS_ASSET_ID;

