CREATE OR REPLACE FORCE VIEW V_CCLAIM_LAST_VER AS
SELECT "SD_1","C_CLAIM_ID","C_CLAIM_HEADER_ID","SEQNO","DECLARE_SUM","CLAIM_STATUS_ID","ASSET_OF_VICTIM","COMPENSATE_DAMAGE_SUM","ACCOUNT_PAYMENT","BENEFICIARY_SUM","DAMAGE_PAYMENT_SUM","PAYMENT_SUM","INTERPAYMENT_SUM","ADDITIONAL_EXPENSES_SUM","ADDITIONAL_EXPENSES_OWN_SUM","ADDITIONAL_EXPENSES_NOOWN_SUM","FILIAL_ID","CLAIM_STATUS_DATE" FROM 
(SELECT MAX (CL.SEQNO) OVER (PARTITION BY CL.C_CLAIM_HEADER_ID) AS sd_1, 
 CL.* 
 FROM C_CLAIM CL) a 
WHERE sd_1 = a.SEQNO;

