create or replace view v_cn_address as
select a.id,
       a.ent_id,
       a.zip,
       a.province_name,
       a.province_type,
       a.city_name,
       a.city_type,
       a.street_name,
       a.street_type,
       a.district_name,
       a.district_type,
       a.region_name,
       a.region_type,
       a.country_id,
       c.description country_name,
  	   a.house_nr,
       a.house_type,
       a.appartment_nr,
       a.remarks,
       a.pob,
       a.building_name,
       a.box_number,
       a.block_number,
       a.name,
       a.region_code,
       a.code,
       a.actual,
       a.actual_date,
       a.decompos_permis,
       a.code_kladr_province,
       a.code_kladr_region,
       a.code_kladr_city,
       a.code_kladr_distr,
       a.code_kladr_street,
       a.code_kladr_doma,
       a.index_province,
       a.index_region,
       a.index_city,
       a.index_distr,
       a.index_street,
       a.index_doma,
       a.PARENT_ADDR_ID,
       a.FACT_ADDR_ID
  from ins.cn_address a,
       ins.t_country  c
 where c.id = a.country_id;
