CREATE OR REPLACE VIEW V_CN_CONTACT_ADDRESS AS
select ca.id contact_address_id,
       ca.contact_id,
       ca.address_type,
       tat.description address_type_name,
       ca.adress_id,
       v."ID",
       v."ENT_ID",
       v."ZIP",
       v."COUNTRY_ID",
       v."COUNTRY_NAME",
       v."PROVINCE_NAME",
       v."PROVINCE_TYPE" PROVINCE_TYPE_NAME,
       v."CITY_NAME",
       v."CITY_TYPE" CITY_TYPE_NAME,
       v."STREET_NAME",
       v."STREET_TYPE" STREET_TYPE_NAME,
       v."DISTRICT_NAME",
       v."DISTRICT_TYPE" DISTRICT_TYPE_NAME,
       v."REGION_NAME",
       v."REGION_TYPE" REGION_TYPE_NAME,
       v."HOUSE_NR",
       v.house_type,
       v."APPARTMENT_NR",
       v."REMARKS",
       v."POB",
       v."BUILDING_NAME",
       v."BOX_NUMBER",
       v."BLOCK_NUMBER",
       v."NAME",
       nvl(v.NAME,pkg_contact.get_address_name(ca.adress_id)) address_name,
       ca.is_default,
       v.region_code,
       ca.status,
       v.code,
       v.actual,
       v.actual_date,
       v.decompos_permis,
       v.code_kladr_province,
       v.code_kladr_region,
       v.code_kladr_city,
       v.code_kladr_distr,
       v.code_kladr_street,
       v.code_kladr_doma,
       v.index_province,
       v.index_region,
       v.index_city,
       v.index_distr,
       v.index_street,
       v.index_doma,
       v.PARENT_ADDR_ID,
       v.FACT_ADDR_ID,
       (CASE WHEN tat.description NOT LIKE '%Фактический по КЛАДР%'
             THEN tat.sort_order
             ELSE (SELECT tadr.sort_order
                   FROM ins.t_address_type tadr
                   WHERE tadr.description = regexp_replace(tat.description,' \(Фактический по КЛАДР\)')
                   )
        END) sort_order_addr_type
  from ins.cn_contact_address ca,
       ins.t_address_type     tat,
       ins.v_cn_address       v
 where ca.address_type = tat.id
   and ca.adress_id = v.id;
