CREATE OR REPLACE FORCE VIEW V_PRODUCT_STATUS_CURRENT AS
SELECT "SD_1","T_PRODUCT_VERSION_ID","PRODUCT_ID","VERSION_NR","VERSION_STATUS","START_DATE","END_DATE","ADVANCE_SALE_DAYS","MAX_POLICY_PERIOD","MIN_POLICY_PERIOD","MIN_PACKAGE_NUMBER","PROPOSAL_VALID_DAYS","END_DATE_RULE_ID","END_DATE_DAY","END_DATE_MONTH","ENT_ID","FILIAL_ID","EXT_ID" FROM 
(SELECT MAX (PV.VERSION_NR) OVER (PARTITION BY PV.PRODUCT_ID) AS sd_1, 
 PV.* 
 FROM T_PRODUCT_VERSION PV) a 
WHERE sd_1 = a.version_nr;

