CREATE OR REPLACE FORCE VIEW V_RE_COVER AS
(
SELECT RE_COVER_ID, P_COVER_ID, START_DATE, END_DATE, CANCEL_DATE, 
 BRUTTO_PREMIUM, COMMISSION, NETTO_PREMIUM, RETURN_PREMIUM, ENT_ID, 
 FILIAL_ID, RE_SLIP_ID, PART_SUM, FUND_ID, FUND_PAY_ID, 
 T_INSURANCE_GROUP_ID, INS_POLICY, INS_ASSET, CUSTOMER_ID, INS_AMOUNT, 
 INS_PREMIUM, INS_TARIFF, RE_M_CONTRACT_ID, EXT_ID, RE_BORDERO_ID, 
 RE_CONTRACT_VER_ID, P_ASSET_HEADER_ID, T_PRODUCT_LINE_ID, PERIL_ID, FLG_MANUAL, 
 FLG_CALC, RE_TARIF, FLG_CUR_VERSION, DELTA_BRUTTO, DELTA_COMMISSION, 
 ID_DOC FROM (
SELECT rc.*, rc.re_contract_ver_id id_doc FROM re_cover rc WHERE rc.re_contract_ver_id IS NOT NULL
UNION
SELECT rc.*, rc.re_slip_id id_doc FROM re_cover rc WHERE rc.re_slip_id IS NOT NULL));

