CREATE OR REPLACE FORCE VIEW V_T_KLADR_KLADR_ORIG AS
SELECT ko.name,
       ko.socr,
       ko.code,
       ko.pindex,
       ko.gninmb,
       ko.uno,
       ko.ocatd,
       ko.status,
       '' korp,
       '' oldcode,
       '' newcode,
       '' plevel,
       'KLADR' file_name,
       '' scname,
       '' socrname,
       '' kod_t_st,
       ko.load_id,
       ko.load_date
FROM ins.t_kladr_orig ko
UNION ALL
SELECT so.name,
       so.socr,
       so.code,
       so.pindex,
       so.gninmb,
       so.uno,
       so.ocatd,
       '',
       '' korp,
       '' oldcode,
       '' newcode,
       '' plevel,
       'STREET' file_name,
       '' scname,
       '' socrname,
       '' kod_t_st,
       so.load_id,
       so.load_date
FROM ins.t_street_orig so
UNION ALL
SELECT do.name,
       do.socr,
       do.code,
       do.pindex,
       do.gninmb,
       do.uno,
       do.ocatd,
       '',
       do.korp,
       '' oldcode,
       '' newcode,
       '' plevel,
       'DOMA' file_name,
       '' scname,
       '' socrname,
       '' kod_t_st,
       do.load_id,
       do.load_date
FROM ins.t_doma_orig do
UNION ALL
SELECT '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       ao.oldcode,
       ao.newcode,
       ao.plevel,
       'ALTNAMES' file_name,
       '' scname,
       '' socrname,
       '' kod_t_st,
       ao.load_id,
       ao.load_date
FROM ins.t_altnames_orig ao
UNION ALL
SELECT '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       '',
       sco.plevel,
       'SOCRBASE' file_name,
       sco.scname,
       sco.socrname,
       sco.kod_t_st,
       sco.load_id,
       sco.load_date
FROM ins.t_socrbase_orig sco;

