CREATE OR REPLACE FORCE VIEW V_T_Q_QUEST_ENABL AS
SELECT QQ.Q_QUESTIONS_ID,
       QPL.T_Q_PL_QUESTIONS_ID,
       CASE WHEN NVL(QPL.DEFAULT_CAN_CHANGE,1)=0 THEN 0 
       ELSE
       (NVL((SELECT CASE WHEN NVL(QQ1.ANSWER_VALUE,0) = 0 THEN 0
                    ELSE 1
                    END
             FROM Q_QUESTIONS QQ1,
                  T_Q_VALUE_TYPE QVT
            WHERE QQ1.T_Q_PL_QUESTIONS_ID = QPL.PARENT_PL_QUESTION_ID
              AND QVT.T_Q_VALUE_TYPE_ID = QQ1.T_Q_VALUE_TYPE_ID
              AND qq1.q_quest_form_id = qq.q_quest_form_id
              AND QVT.BRIEF = 'BOOLEAN'),1))
       END IS_ENABLED
  FROM Q_QUESTIONS QQ,
       T_Q_PL_QUESTIONS QPL,
       Q_QUEST_FORM QF
 WHERE QQ.Q_QUEST_FORM_ID = QF.Q_QUEST_FORM_ID
   AND QQ.T_Q_PL_QUESTIONS_ID = QPL.T_Q_PL_QUESTIONS_ID
WITH READ ONLY;

