create or replace force view vgo_gate_account as
select "ACCOUNT_ID" as CODE,"PARENT_ID","ACC_CHART_TYPE_ID","NAME","NUM","CHARACTERISTICS","OPEN_DATE","CLOSE_DATE","FUND_ID","ACC_STATUS_ID","IS_REVALUED","IS_SYNTH","A1_ANALYTIC_TYPE_ID","A2_ANALYTIC_TYPE_ID","A3_ANALYTIC_TYPE_ID","A4_ANALYTIC_TYPE_ID","A5_ANALYTIC_TYPE_ID","A1_URO_ID","A2_URO_ID","A3_URO_ID","A4_URO_ID","A5_URO_ID","A1_URE_ID","A2_URE_ID","A3_URE_ID","A4_URE_ID","A5_URE_ID","ACC_ROLE_ID","EXTERNAL_ID" from ins.account;

